[package]
name = "qmlextensionplugins"
version = "0.1.0"
edition = "2018"
authors = ["Olivier Goffart <olivier.goffart@slint.dev>"]

[lib]
name = "qmlqtimeexampleplugin"
crate-type = ["cdylib"]

[dependencies]
qmetaobject = { path = "../../qmetaobject" }
chrono = "^0.4"
cstr = "0.2"
